# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('connection', models.CharField(choices=[('FTP', 'FTP'), ('FTPS', 'FTPS'), ('SFTP', 'SFTP')], max_length=10)),
                ('server_type', models.CharField(choices=[('FAST DL', 'FAST DL'), ('FAST DL PUBLIC', 'FAST DL PUBLIC'), ('SERVER', 'SERVER'), ('SERVER PUBLIC', 'SERVER PUBLIC')], max_length=10)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('host_address', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('map_cycle_location', models.CharField(max_length=64)),
                ('map_location', models.CharField(max_length=64)),
                ('home_location', models.CharField(max_length=64)),
            ],
        ),
    ]
