# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('FAST DL', 'FAST DL'), ('FAST DL PUBLIC', 'FAST DL PUBLIC'), ('SERVER', 'SERVER'), ('SERVER PUBLIC', 'SERVER PUBLIC')], max_length=20),
        ),
    ]
