# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20171123_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploaderpermissions',
            options={'managed': False, 'permissions': (('uploader_access', 'Has access to the uploader'), ('uploader_admin', 'Has uploader admin access'))},
        ),
    ]
