# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('access_uploader', 'Can access the uploader'),)},
        ),
    ]
