# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171119_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('access_uploader', 'Can access the uploader'), ('uploader_advanced', 'Has access to the advanced uploader options'))},
        ),
    ]
