# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171120_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('uploader_access', 'Can access the uploader'), ('uploader_admin', 'Has access to the advanced uploader options'))},
        ),
    ]
